### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by benmoran56** [kxgames/glooey#1]
I came across your library and would like to try it out, but the Readme seems to be a bit out of date. I'll get a crash with "AttributeError: module 'glooey' has no attribute 'Background'".
I cloned the repository and found that most of the tests failed as well. 
Are there are current working examples available, or is this in the middle of a re-write? 

Thanks!

**Comment by kalekundert** [comment]
Sorry for the slow reply; for some reason I missed the email from github.

I'm not sure why you're getting that AttributeError.  The README was a little out of date (fixed now), but it should've still run.  Maybe try pulling again.  The code isn't in the middle of a rewrite per se, but I have been developing it a lot and ``master`` isn't always stable.  I just pushed 9e60587, and as far as I know that commit is totally functional (i.e. all the tests pass for me).

**Comment by benmoran56** [comment]
Thanks for the reply. I gave it another try, and it did work successfully after a pip install -e into a virtual environment. All of the demos I've tried worked OK (one of them needed the docopt module). It looks like a fantastic library, especially with themes. I'm not sure what the issue was before, but as long as it's working now.
