### ISSUE TITLE
on_click function doesn't work

### ISSUE THREAD

**Issue by miswanting** [kxgames/glooey#13]
I use glooey to build my main menu, it is fine and respond correctly when my mouse over it.
Everything is just good except on_click function. No respond.
Then I tried the example below and it shows good but when I click it, it just doesn't respond, too.
http://glooey.readthedocs.io/en/latest/_downloads/button.py
What's the problem?

Python 3.6.3 on Windows 10
Anaconda 5.0.1

**Comment by benmoran56** [comment]
This is not my project, but I think there may be a general bug related to mouse click/release. 
Please try this simple script here, and see if you have the same problem: 
https://bitbucket.org/pyglet/pyglet/issues/130/mouse-release-event-not-triggered

**Comment by miswanting** [comment]
@benmoran56 I tried the code and there's only releases.
It seems like a bug of pyglet, right?

**Comment by benmoran56** [comment]
Yes, this is a pyglet bug. If you are installing from pip, can you try upgrading to the current alpha version? 
`pip install pyglet==1.4.0a1`

**Comment by miswanting** [comment]
@benmoran56 It works! Thank you for your help!

**Comment by benmoran56** [comment]
No worries!
