### ISSUE TITLE
Small bug in the root class

### ISSUE THREAD

**Issue by BerndSerker** [kxgames/glooey#15]
Hey, I really like the project you have greated with gloomey. Found a minor bug. In [root.py](https://github.com/kxgames/glooey/blob/master/glooey/root.py) on line 118, if you rename "self.repack()" to "self._repack()", the widgets adapt dynamically if you resize the window. Otherwise you get an error. Would be great if you could fix this as its only a typo ;)

Please continue the great work (Y)

**Comment by kalekundert** [comment]
Sorry for being unresponsive; for some reason I wasn't getting email notifications for this project.  Thanks for tracking the issue down. I just pushed a fix, you should be able to resize windows again.
