### ISSUE TITLE
The module has no attribute 'Label'

### ISSUE THREAD

**Issue by DomaSherif** [kxgames/glooey#19]
I copied the Code that in the "Read me" GitHub and it gave me this Error:
```Traceback (most recent call last):
  File "C:\Users\Adam\Desktop\testing\glooey.pyw", line 4, in <module>
    import glooey
  File "C:\Users\Adam\Desktop\testing\glooey.pyw", line 10, in <module>
    class MyLabel(glooey.Label):
AttributeError: module 'glooey' has no attribute 'Label'```

**Comment by kalekundert** [comment]
I think the problem is that your script is named ``glooey.pyw``.  That will cause ``import glooey`` to import your script, rather than the actual ``glooey`` library, which I believe is the cause of the error you're seeing.
