### ISSUE TITLE
Weird behaviour with composite alignment

### ISSUE THREAD

**Issue by UplinkPhobia** [kxgames/glooey#21]
When trying to create a VBox with a "composite" alignment (e.g. "fill left"), the alignment completely messes up.
The following code is a minimal way to show it.
```python
import glooey
import pyglet

win = pyglet.window.Window(800, 600)

gui = glooey.Gui(win)

box = glooey.VBox()
box.padding = 100 
box.alignment = "fill left"
gui.add(box)

p = glooey.Placeholder(50, 50)
box.add(p)

box.debug_placement_problems()
pyglet.app.run()
```

![bug](https://user-images.githubusercontent.com/24713223/52763388-ce9a9c00-301b-11e9-91e8-0600aa5bfcbd.png)

Instead of filling the left side as expected, the content sticks to the bottom side.

Is it an expected behaviour, or is there something wrong with the way it behaves?

**Comment by kalekundert** [comment]
Thanks for the bug report and the nice minimal example.  I poked around a little, and can definitely reproduce the bug.  I get the right behavior with `box.padding = 0`, so it seems like the issue is that the padding is not being correctly handled somehow.  I'll try to track this down more specifically in the next few days.

**Comment by UplinkPhobia** [comment]
I did a few more tests, and apparently even with no explicit padding it's possible to recreate the bug (it is probably due to padding anyway, but implicitely created by stacking up widgets).
Here's what I used :
```python
import glooey
import pyglet

win = pyglet.window.Window(800, 600)

gui = glooey.Gui(win)

box = glooey.VBox()
gui.add(box)

side_pane = glooey.VBox()
side_pane.alignment = "fill left"  # Toggling this line toggles the bug
box.add(side_pane)
p = glooey.Placeholder(50, 50)
side_pane.add(p)

# This placeholder is just used to show the bug, no padding or alignment
# since we don't want to make it bug too
p = glooey.Placeholder(50, 50) 
box.add(p)


box.debug_placement_problems()
pyglet.app.run()
```

My first example showed that padding on a VBox was showing the bug, but from this new little example it seems that putting a VBox inside of another, even without padding, will make it bug if you add alignment constraints. 
However I can't tell whether it's because widgets inside of the VBox have an implicit padding that recreates the bug, or whether it's because the bug isn't limited/due to padding.

**Comment by kalekundert** [comment]
This should be fixed now.  There was a bug in the 'fill left' alignment function that basically resulted in widgets being stuck to the bottom of the window, no matter what.  Similar problems in 'fill right', 'fill top', and 'fill bottom' were also fixed.
