### ISSUE TITLE
Parameters for Frames' Decoration class

### ISSUE THREAD

**Issue by UplinkPhobia** [kxgames/glooey#23]
I'd like to create a Frame using a custom Background that uses a variable parameter.

The thing I'd logically want to do is something like 
```python3
class MyFrame(glooey.Frame):
    def __init__(self):
        super().__init__()
        self.decoration_layer = MyBackground("variable parameter")
```

Would there be an easy way to do this that I don't know? I'd like to do it properly, but I don't see any clean way to.

**Comment by kalekundert** [comment]
That's a good comment; I don't think there was an easy way to do that.  I just added a `decoration` setter to `Frame` that should do what you want, though.  If you pull the latest commit, the following should work:
```py
class MyFrame(glooey.Frame):
    def __init__(self):
        super().__init__()
        self.decoration = MyBackground("variable parameter")
```
Let me know if anything doesn't work.  Obviously I just wrote this code, so it's definitely possible that I made some mistake.

**Comment by UplinkPhobia** [comment]
Thanks for the very quick fix, it seems to be working nicely :)
