### ISSUE TITLE
Disabling checkboxes before adding to GUI only updates on rollover

### ISSUE THREAD

**Issue by PythonPr0** [kxgames/glooey#25]
Creating a checkbox and disabling it before adding it to the GUI causes it to be rendered in its enabled state until the mouse is moved over it. Is this intended?

**Comment by kalekundert** [comment]
Thanks for the bug report!  I should be able to look at it this weekend.

**Comment by kalekundert** [comment]
Should be fixed now, let me know if you have any other problems.

**Comment by PythonPr0** [comment]
Yep that fixed the problems thanks!
