### ISSUE TITLE
Resizing window when a Form has focus

### ISSUE THREAD

**Issue by PythonPr0** [kxgames/glooey#26]
If a form has focus and the window resizes everything breaks. Is this a pyglet issue or glooey?

**Comment by kalekundert** [comment]
Definitely sounds like a glooey issue.  I'm planning to take a look at this later tonight.

**Comment by kalekundert** [comment]
It took me a while to figure out what was going on with this one, but it should be fixed now.  Briefly, the problem was that the Form was creating multiple "caret" objects, and events were still being routed to the stale carets.  Let me know if any sort of buggy behavior persists.
