### ISSUE TITLE
Typo in the PyPi project

### ISSUE THREAD

**Issue by PythonPr0** [kxgames/glooey#31]
This is the current file (and line) for the widget class https://github.com/kxgames/glooey/blob/609b2989b17658c8823fbb76da27c8d0b1ec9172/glooey/widget.py#L1310-L1320 but having installed it via pip there is what appears to be a typo (for a random function p): 
![image](https://user-images.githubusercontent.com/32309654/58103795-8327f900-7bdb-11e9-8a1b-34da64b54330.png)
This throws an error, so I didn't think it was intentional!

**Comment by kalekundert** [comment]
That's what I get for making a release on code I was in the middle of debugging, and not having the greatest automated tests. :-)

Should be fixed now, try upgrading to `0.2.1`.

**Comment by PythonPr0** [comment]
Yep that's fixed now
