### ISSUE TITLE
Unnecessary Hash-bang in files

### ISSUE THREAD

**Issue by expeditioneer** [kxgames/glooey#44]
The Hash-bang `#!/usr/bin/env python3` in each file is unnecessary, because AFAICS the files are not intended to be executed. The Hash-bang leads to confiusion, could this be removed and only put in place where it is necessary?

**Comment by kalekundert** [comment]
You're right that those lines aren't really necessary, but I like that they clarify that the code is for python3 as opposed to python2.  My editor also uses those lines to decide how some things should be syntax-highlighted, e.g. print.  So unless there's a more concrete problem that these lines are causing, I'd like to keep them.
