### ISSUE TITLE
main icon and title change

### ISSUE THREAD

**Issue by akshaypatel1811** [kxgames/glooey#48]
Hi,

@kalekundert , @wkentaro . I am new to this library. Can we change the main logo/icon? right now it's python kernel logo. and also can we change the title of the GUI? right now it shows the path where it is in my PC.

![Capture](https://user-images.githubusercontent.com/50308147/112893260-706c8e00-90a8-11eb-93f5-174507a10aea.PNG)

Thank you,
Akshay

**Comment by kalekundert** [comment]
Sorry for the slow response.  If I'm understanding you correctly, you want to change the title/icon of the GUI window?  If so, you can  do that using pyglet.  See the [windowing](https://pyglet.readthedocs.io/en/latest/programming_guide/windowing.html#appearance) documentation.

**Comment by akshaypatel1811** [comment]
Thank you @kalekundert .
